[package]
name = "evolutionary"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
csv = "1.3.1"
ndarray = "0.16.1"
rand = "0.9.2"

[dev-dependencies]
flamegraph = "0.6.9"
